### ISSUE TITLE
Do not work with nested selectors

### ISSUE THREAD

**Issue by msaktype** [morishitter/postcss-ref#1]
e.g.

``` css
.foo > .nested {
  font-size: 12px;
  color: #333;
}

.bar {
  @ref .foo > .nested font-size;
}
```
