### ISSUE TITLE
Potential concern with how ref works with custom properties/var

### ISSUE THREAD

**Issue by gavinmcfarland** [morishitter/postcss-ref#11]
I really like this plugin by the way. However, there is one area I wanted to get your thoughts on.

When referencing a custom property one concern is that if the custom property is superseded by another rule then the reference will no longer make sense.

For example

```css
.foo {
  --font-m: 12px;
  color: blue;
}

.bar {
  --font-m: 18px;
  color: red;
}
 
.baz {
  font-size: ref(.foo, --font-m);
}
```

The output will be

```css
.foo {
  --font-m: 12px;
  color: blue;
}

.bar {
  --font-m: 24px;
  color: red;
}
 
.baz {
  font-size: var(--font-m);
}
```

In this scenario, the `font-size` of `.baz` may be `12px` or `24px` depending on how they are applied in the HTML, but `ref(.foo, --font-m)` gives the impression it will be 12px.

Therefore it may make sense to use `var(--font-m)` for these occasions instead. And instead when a custom property is referenced it worth referencing the value directly instead.

So the output would instead be

```css
.foo {
  --font-m: 12px;
  color: blue;
}

.bar {
  --font-m: 24px;
  color: red;
}
 
.baz {
  font-size: 24px;
}
```

There could maybe be another way to handle this but it would be much more complex which would involve changing the ordering of the rules and I'm not sure if it would provide much use, or what the use case would be.

I'm interested to hear your thoughts. Many thanks.
