### ISSUE TITLE
Allow an option to be able to use ref as a function

### ISSUE THREAD

**Issue by dan-gamble** [morishitter/postcss-ref#3]
i.e. instead of:

``` css
.foo {
  font-size: 14px;
}

.bar {
  @ref .foo, font-size, font-size;
}
```

You can do:

``` css
.foo {
  font-size: 14px;
}

.bar {
  font-size: ref(.foo, font-size);
}
```

I've already written a lot of this in a PR i'll submit soon. Would like some thoughts on it :)
