### ISSUE TITLE
Add the ability to reference @media selectors

### ISSUE THREAD

**Issue by dan-gamble** [morishitter/postcss-ref#5]
It would be nice to be able to do

``` css
.foo {
  font-size: 10px;
}

@media (min-width: 1602px) {
  .foo {
    font-size: 12px;
    color: #333;
  }
}

.bar {
  @ref @media (min-width: 1602px) .foo, font-size;
}
```

or

```
.bar {
  font-size: ref(@media (min-width: 1602px) .foo, font-size);
}
```
